# Generated by Django 3.2 on 2023-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_yamdb', '0002_auto_20230831_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
