# Generated by Django 3.2 on 2023-09-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_yamdb', '0002_auto_20230909_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
    ]
