# Generated by Django 3.2 on 2023-09-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_yamdb', '0003_auto_20230902_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
